# Sets the build environment.
sudo: required
dist: bionic

language: cpp
matrix:
  include:
    - env: PYTHON="3.6" CONDA_PY=36 ARCH="x86_64"
      os: linux
      dist: bionic
    - env: PYTHON="3.7" CONDA_PY=37 ARCH="x86_64"
      os: linux
      dist: bionic

before_install:
  # See https://docs.travis-ci.com/user/installing-dependencies#installing-packages-from-a-custom-apt-repository
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install g++-9 libxi-dev

  # Use GCC 9
  - export CC=gcc-9
  - export CXX=g++-9

  # Install minconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build
  - conda install anaconda-client
  - conda config --add channels conda-forge
  - git clone https://github.com/pybind/pybind11.git pybind11

script:
  - conda build ci/conda

after_success:
  - anaconda -t $CONDA_UPLOAD_TOKEN upload $HOME/miniconda/conda-bld/linux-64/pyocct*.bz2 -l $TRAVIS_BRANCH --force
